### ISSUE TITLE
ローカル環境作成時のつまづきポイント

### ISSUE THREAD

**Issue by gooduser2034** [velvia1222/travelbrochure#1]
vagrant@ubuntu-xenial:~$ anyenv install goenv
anyenv: command not found

**Comment by gooduser2034** [comment]
ここも

vagrant@ubuntu-xenial:~$ goenv install 1.9.1
No command 'goenv' found, did you mean:
 Command 'gbenv' from package 'gbutils' (universe)
goenv: command not found

**Comment by gooduser2034** [comment]
vagrant@ubuntu-xenial:~$ ndenv install v8.5.0
ndenv: command not found

**Comment by velvia1222** [comment]
〜envをインストールした後に.bashrcを読み込み直さないとインストールが反映されないため、command not foundがおきています。
〜envインストール後の手順に「. ~/.bashrc」を追加しました。
